# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bash_pb2 as bash__pb2


class BashServiceStub(object):
    """bash 服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageRecheck = channel.unary_unary(
            '/service_bash.BashService/ImageRecheck',
            request_serializer=bash__pb2.ImageRecheckRequest.SerializeToString,
            response_deserializer=bash__pb2.ImageRecheckReply.FromString,
        )


class BashServiceServicer(object):
    """bash 服务
    """

    def ImageRecheck(self, request, context):
        """图片复判接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BashServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ImageRecheck': grpc.unary_unary_rpc_method_handler(
            servicer.ImageRecheck,
            request_deserializer=bash__pb2.ImageRecheckRequest.FromString,
            response_serializer=bash__pb2.ImageRecheckReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'service_bash.BashService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class BashService(object):
    """bash 服务
    """

    @staticmethod
    def ImageRecheck(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service_bash.BashService/ImageRecheck',
                                             bash__pb2.ImageRecheckRequest.SerializeToString,
                                             bash__pb2.ImageRecheckReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
